In [18]:
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path
import matplotlib.pyplot as plt


ML_DIR = Path("ml")
ML_DIR.mkdir(parents=True, exist_ok=True)


pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

In [36]:
full_df = pd.read_csv('ml/runtimes.csv') 
full_df.head()

,symbol,regularMarketPrice,regularMarketChangePercent,regularMarketVolume,averageDailyVolume3Month,marketCap,VolumeSpike,MomentumScore,VolumeScore,VolatilityScore,TrendScore,HotScore_today,HotScore_avg,RuntimeScore
0,AA,62.455,6.925187,11071607.0,7633285.0,1.647954e+10,1.450438,0.982394,0.922535,0.834507,0.742958,0.907923,0.904854,0.955657
1,AAOI,77.755,44.822124,10952941.0,5039413.0,5.309103e+09,2.173456,1.000000,0.971963,0.990654,0.803738,0.968692,0.957172,0.990363
2,AAON,109.260,7.964432,366664.0,984116.0,8.919337e+09,0.372582,0.903382,0.603865,0.874396,0.850242,0.787440,0.652053,0.997535
3,ACLX,113.805,77.515205,17137837.0,1083556.0,6.580532e+09,15.816291,1.000000,1.000000,1.000000,0.964286,0.996429,0.995114,0.998875
4,ADEA,21.720,9.301148,1395921.0,849807.0,2.378561e+09,1.642633,0.967105,0.944079,0.736842,0.832237,0.899507,0.811025,1.004302

In [37]:

from engine.filters import apply_filters

df_filtered = apply_filters(full_df)
df_filtered.head(20)

,symbol,regularMarketPrice,regularMarketChangePercent,regularMarketVolume,averageDailyVolume3Month,marketCap,VolumeSpike,MomentumScore,VolumeScore,VolatilityScore,TrendScore,HotScore_today,HotScore_avg,RuntimeScore
0,AA,62.4550,6.925187,11071607.0,7633285.0,1.647954e+10,1.450438,0.982394,0.922535,0.834507,0.742958,0.907923,0.904854,0.955657
1,AAOI,77.7550,44.822124,10952941.0,5039413.0,5.309103e+09,2.173456,1.000000,0.971963,0.990654,0.803738,0.968692,0.957172,0.990363
3,ACLX,113.8050,77.515205,17137837.0,1083556.0,6.580532e+09,15.816291,1.000000,1.000000,1.000000,0.964286,0.996429,0.995114,0.998875
4,ADEA,21.7200,9.301148,1395921.0,849807.0,2.378561e+09,1.642633,0.967105,0.944079,0.736842,0.832237,0.899507,0.811025,1.004302
5,ADSK,248.0000,6.232599,2674117.0,1943206.0,5.282400e+10,1.376137,0.924303,0.868526,0.968127,0.948207,0.915936,0.912007,0.960122
6,AEIS,309.5300,10.926745,1088461.0,569275.0,1.168336e+10,1.912013,0.953659,0.885366,0.970732,0.939024,0.931707,0.932888,0.965221
8,AGRO,15.3300,9.110318,3039855.0,1154350.0,2.185702e+09,2.633391,0.992958,0.978873,0.633803,0.820423,0.898944,0.894214,0.952116
9,AGX,465.9150,12.485513,653109.0,362415.0,6.463830e+09,1.802103,0.977324,0.895692,0.988662,0.975057,0.950794,0.948953,0.976367
10,AIR,118.5200,9.934140,1172160.0,496723.0,4.690134e+09,2.359786,0.962306,0.942350,0.964523,0.935698,0.953104,0.953104,0.976552
11,AKAM,104.6100,10.348099,10380959.0,3252240.0,1.504974e+10,3.191941,0.972136,0.922601,0.894737,0.792570,0.921362,0.919320,0.961792
14,AMD,214.3944,9.051062,51167845.0,35335240.0,3.495510e+11,1.448068,0.960000,0.948571,0.974286,0.422857,0.905143,0.894376,0.958591
15,AMRZ,64.3400,12.110119,5909735.0,4153326.0,3.558530e+10,1.422892,0.970238,0.961310,0.851190,0.571429,0.903423,0.903423,0.951711
16,ANET,148.4600,9.872715,11501795.0,7835524.0,1.869535e+11,1.467904,0.962466,0.916890,0.962466,0.630027,0.913271,0.913271,0.956635
17,APGE,78.5300,7.575341,3485597.0,961793.0,5.406606e+09,3.624062,0.920177,0.975610,0.904656,0.871397,0.931596,0.931596,0.965798
18,APP,478.3500,8.990861,6413646.0,5662945.0,1.616608e+11,1.132564,0.947619,0.859524,0.992857,0.900000,0.921071,0.903202,0.970428
19,ARM,157.0700,16.382631,29484555.0,5828967.0,1.668081e+11,5.058281,0.993348,0.986696,0.991131,0.758315,0.967073,0.967073,0.983537
23,AVAV,297.4350,17.912785,1551398.0,1408805.0,1.485159e+10,1.101216,0.995169,0.951691,0.995169,0.917874,0.972222,0.968369,0.988101
25,AXTI,44.4600,15.300823,12721093.0,7297096.0,2.457489e+09,1.743309,0.996979,0.909366,0.921450,0.643505,0.915861,0.915861,0.957931
26,AZN,204.7600,5.873840,3202871.0,362680.0,3.174360e+11,8.831121,0.896882,0.988010,0.913669,0.944844,0.936930,0.936422,0.968737
27,BBIO,74.3200,13.223645,6120877.0,2840896.0,1.440789e+10,2.154559,0.985163,0.931751,0.964392,0.833828,0.947181,0.947181,0.973591

In [34]:
full_df.shape

(187, 14)

In [41]:

from engine.scoring import compute_scores
scores_df = compute_scores(df_filtered)
scores_df.head(25)

,symbol,regularMarketPrice,regularMarketChangePercent,regularMarketVolume,averageDailyVolume3Month,marketCap,VolumeSpike,MomentumScore,VolumeScore,VolatilityScore,TrendScore,HotScore_today,HotScore_avg,RuntimeScore,acceleration,base_score
110,GSIW,20.550,115.408790,556021.0,3172.0,4.482961e+09,175.290353,1.000000,1.000000,0.953947,1.000000,0.990789,0.979347,1.001237,0.011443,26.965082
68,DAWN,21.205,65.923320,76016941.0,2738703.0,2.190427e+09,27.756548,1.000000,1.000000,0.938628,0.754513,0.963177,0.966050,0.980101,-0.002873,4.742463
3,ACLX,113.805,77.515205,17137837.0,1083556.0,6.580532e+09,15.816291,1.000000,1.000000,1.000000,0.964286,0.996429,0.995114,0.998875,0.001315,2.994396
175,NATL,45.290,8.168144,6403046.0,399454.0,3.347118e+09,16.029495,0.956395,1.000000,0.767442,0.936047,0.931831,0.929650,0.967089,0.002181,2.957879
236,TPH,46.310,26.633858,13308719.0,862091.0,4.052427e+09,15.437719,0.997319,1.000000,0.930295,0.804290,0.965550,0.965550,0.982775,0.000000,2.864202
255,VRE,18.815,12.194394,11438966.0,785850.0,2.082186e+09,14.556170,0.994048,0.994048,0.708333,0.875000,0.925000,0.917733,0.966459,0.007267,2.745511
266,XENE,60.850,45.088223,9354564.0,916825.0,4.702184e+09,10.203217,0.996711,0.996711,0.976974,0.911184,0.984211,0.982050,0.993205,0.002161,2.112071
164,MASI,174.520,34.091442,6564766.0,751585.0,9.374159e+09,8.734562,1.000000,0.991870,0.991870,0.959350,0.991463,0.986065,0.998469,0.005398,1.889072
26,AZN,204.760,5.873840,3202871.0,362680.0,3.174360e+11,8.831121,0.896882,0.988010,0.913669,0.944844,0.936930,0.936422,0.968737,0.000508,1.850950
209,SEM,16.240,8.266665,7242555.0,893898.0,2.014039e+09,8.102216,0.973180,1.000000,0.593870,0.846743,0.894061,0.894061,0.947031,0.000000,1.769969
229,TDC,37.880,29.592900,11363211.0,1424086.0,3.579660e+09,7.979301,1.000000,0.985612,0.877698,0.705036,0.941007,0.941015,0.970499,-0.000008,1.735623
159,LMAT,113.690,24.414540,1255515.0,161939.0,2.579171e+09,7.753012,0.997768,0.997768,0.988839,0.986607,0.994866,0.994866,0.997433,0.000000,1.735257
52,CGNX,58.670,36.346733,12539131.0,1772308.0,9.832977e+09,7.075029,0.996904,0.978328,0.944272,0.798762,0.960062,0.958624,0.980781,0.001438,1.616747
269,YOU,46.510,38.960300,9431469.0,1412810.0,6.270828e+09,6.675681,1.000000,0.992736,0.935835,0.740920,0.958717,0.958717,0.979358,0.000000,1.551674
244,UNF,279.980,8.557251,1544058.0,235305.0,5.062546e+09,6.561943,0.965174,1.000000,1.000000,1.000000,0.987811,0.987811,0.993905,0.000000,1.534055
221,SRPT,23.770,34.980125,16921167.0,2612386.0,2.495607e+09,6.477284,1.000000,0.993348,0.915743,0.574279,0.938248,0.938248,0.969124,0.000000,1.491878
102,GLBE,34.810,17.205389,8382467.0,1444380.0,5.908165e+09,5.803505,0.993023,0.995349,0.853488,0.711628,0.937791,0.937718,0.968934,0.000073,1.398419
79,ELVN,35.530,14.060992,6318788.0,1098264.0,2.124708e+09,5.753433,0.984479,0.991131,0.864745,0.784922,0.942905,0.942905,0.971452,0.000000,1.396671
272,ZIM,28.900,30.180174,23325255.0,4201090.0,3.481222e+09,5.552191,0.991870,0.983740,0.853659,0.658537,0.928049,0.917691,0.969668,0.010358,1.366734
126,INGM,24.215,13.419202,2192250.0,415100.0,5.692284e+09,5.281258,0.992337,0.992337,0.750958,0.938697,0.938697,0.938697,0.969349,0.000000,1.360589
54,CLDX,30.820,24.074072,3740543.0,694563.0,2.047973e+09,5.385463,0.987893,0.975787,0.825666,0.782082,0.930630,0.931268,0.964972,-0.000639,1.353646
170,MRVL,89.440,18.181822,81158833.0,14770798.0,7.812135e+10,5.494546,0.996390,0.996390,0.963899,0.696751,0.959928,0.964412,0.977639,-0.004485,1.342608
132,IPGP,150.150,35.392240,1798626.0,363096.0,6.339321e+09,4.953583,0.994118,0.973529,0.988235,0.964706,0.982794,0.980803,0.992412,0.001992,1.321058
195,PSKY,13.980,25.044716,50337419.0,9095886.0,1.542228e+10,5.534086,0.996016,0.988048,0.729084,0.322709,0.872510,0.869770,0.937830,0.002740,1.311482
59,CORT,40.470,19.662926,11718296.0,2294335.0,4.304956e+09,5.107491,0.995565,0.988914,0.924612,0.698448,0.949335,0.949335,0.974667,0.000000,1.289606

In [45]:
candidates = scores_df.head(5)[
        [
            "symbol",
            "marketCap",
            "VolumeSpike",
            "MomentumScore",
            "VolatilityScore",
            "TrendScore",
            "RuntimeScore"
        ]
    ].to_dict(orient="records")

for candidate in candidates:
    display(candidate)

{'symbol': 'GSIW',
 'marketCap': 4482961408.0,
 'VolumeSpike': 175.29035308953345,
 'MomentumScore': 1.0,
 'VolatilityScore': 0.9539473684210528,
 'TrendScore': 1.0,
 'RuntimeScore': 1.001236727808336}

{'symbol': 'DAWN',
 'marketCap': 2190427392.0,
 'VolumeSpike': 27.75654789876814,
 'MomentumScore': 1.0,
 'VolatilityScore': 0.9386281588447654,
 'TrendScore': 0.7545126353790613,
 'RuntimeScore': 0.9801012758268618}

{'symbol': 'ACLX',
 'marketCap': 6580531712.0,
 'VolumeSpike': 15.81629099003651,
 'MomentumScore': 1.0,
 'VolatilityScore': 1.0,
 'TrendScore': 0.9642857142857144,
 'RuntimeScore': 0.9988750449614372}

{'symbol': 'NATL',
 'marketCap': 3347118336.0,
 'VolumeSpike': 16.029495261031308,
 'MomentumScore': 0.9563953488372092,
 'VolatilityScore': 0.7674418604651163,
 'TrendScore': 0.936046511627907,
 'RuntimeScore': 0.9670887892411884}

{'symbol': 'TPH',
 'marketCap': 4052426752.0,
 'VolumeSpike': 15.43771945189081,
 'MomentumScore': 0.9973190348525468,
 'VolatilityScore': 0.9302949061662198,
 'TrendScore': 0.8042895442359249,
 'RuntimeScore': 0.982774798927614}